### ISSUE TITLE
cannot publish to gpr via github actions

### ISSUE THREAD

**Issue by mazgi** [mazgi/express-middleware-redirector#1]
https://github.com/mazgi/express-middleware-redirector/blob/da57711dc1e1bdf4e8b2606be632e12a8f4c587d/.github/workflows/publish-npm-package.yaml#L36

- https://github.com/mazgi/express-middleware-redirector/runs/525590197

```
2020-03-22T15:42:37.1397110Z ##[group]Run can-npm-publish --verbose && npm publish --access public || cat /home/runner/.npm/_logs/*.log
2020-03-22T15:42:37.1397360Z [36;1mcan-npm-publish --verbose && npm publish --access public || cat /home/runner/.npm/_logs/*.log[0m
2020-03-22T15:42:37.1430946Z shell: /bin/bash -e {0}
2020-03-22T15:42:37.1431086Z env:
2020-03-22T15:42:37.1431225Z   NPM_CONFIG_USERCONFIG: /home/runner/work/_temp/.npmrc
2020-03-22T15:42:37.1432189Z   NODE_AUTH_TOKEN: ***
2020-03-22T15:42:37.1432326Z ##[endgroup]
2020-03-22T15:42:39.0401938Z npm ERR! Only absolute URLs are supported
2020-03-22T15:42:39.0402621Z 0 info it worked if it ends with ok
2020-03-22T15:42:39.0402802Z 
2020-03-22T15:42:39.0404127Z npm ERR! A complete log of this run can be found in:
2020-03-22T15:42:39.0405291Z npm ERR!     /home/runner/.npm/_logs/2020-03-22T15_42_38_254Z-debug.log
2020-03-22T15:42:39.0405472Z 
2020-03-22T15:42:39.0406617Z 1 verbose cli [ '/opt/hostedtoolcache/node/10.19.0/x64/bin/node',
2020-03-22T15:42:39.0407452Z 1 verbose cli   '/opt/hostedtoolcache/node/10.19.0/x64/bin/npm',
2020-03-22T15:42:39.0407914Z 1 verbose cli   'view',
2020-03-22T15:42:39.0408772Z 1 verbose cli   '@mazgi/express-middleware-redirector',
2020-03-22T15:42:39.0409239Z 1 verbose cli   'versions',
2020-03-22T15:42:39.0409668Z 1 verbose cli   '--json',
2020-03-22T15:42:39.0410118Z 1 verbose cli   '--registry',
2020-03-22T15:42:39.0410692Z 1 verbose cli   'https://npm.pkg.github.com/' ]
2020-03-22T15:42:39.0410980Z 2 info using npm@6.13.4
2020-03-22T15:42:39.0411224Z 3 info using node@v10.19.0
2020-03-22T15:42:39.0411705Z 4 verbose npm-session 5a918d1f4d7c637d
2020-03-22T15:42:39.0412050Z 5 verbose stack TypeError: Only absolute URLs are supported
2020-03-22T15:42:39.0413000Z 5 verbose stack     at getNodeRequestOptions (/opt/hostedtoolcache/node/10.19.0/x64/lib/node_modules/npm/node_modules/node-fetch-npm/src/request.js:131:11)
2020-03-22T15:42:39.0413971Z 5 verbose stack     at fetch.Promise (/opt/hostedtoolcache/node/10.19.0/x64/lib/node_modules/npm/node_modules/node-fetch-npm/src/index.js:44:21)
2020-03-22T15:42:39.0414323Z 5 verbose stack     at new Promise (<anonymous>)
2020-03-22T15:42:39.0415877Z 5 verbose stack     at fetch (/opt/hostedtoolcache/node/10.19.0/x64/lib/node_modules/npm/node_modules/node-fetch-npm/src/index.js:41:10)
2020-03-22T15:42:39.0416500Z 5 verbose stack     at retry (/opt/hostedtoolcache/node/10.19.0/x64/lib/node_modules/npm/node_modules/make-fetch-happen/index.js:332:14)
2020-03-22T15:42:39.0417406Z 5 verbose stack     at /opt/hostedtoolcache/node/10.19.0/x64/lib/node_modules/npm/node_modules/promise-retry/index.js:29:24
2020-03-22T15:42:39.0417911Z 6 verbose cwd /home/runner/work/express-middleware-redirector/express-middleware-redirector
2020-03-22T15:42:39.0418256Z 7 verbose Linux 5.0.0-1032-azure
2020-03-22T15:42:39.0419101Z 8 verbose argv "/opt/hostedtoolcache/node/10.19.0/x64/bin/node" "/opt/hostedtoolcache/node/10.19.0/x64/bin/npm" "view" "@mazgi/express-middleware-redirector" "versions" "--json" "--registry" "https://npm.pkg.github.com/"
2020-03-22T15:42:39.0419340Z 9 verbose node v10.19.0
2020-03-22T15:42:39.0419516Z 10 verbose npm  v6.13.4
2020-03-22T15:42:39.0419739Z 11 error Only absolute URLs are supported
2020-03-22T15:42:39.0419925Z 12 verbose exit [ 1, true ]
```

**Comment by mazgi** [comment]
from local

```shellsession
node@c54638fec41c:/workspace$ node --version
v10.19.0
node@c54638fec41c:/workspace$ npm --version
6.13.4
node@c54638fec41c:/workspace$ npm "view" "@mazgi/express-middleware-redirector" "versions" "--json" "--registry" "https://npm.pkg.github.com/"
[
  "0.0.1"
]
```

🤔
